name: Node.js CI/CD Pipeline

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: production
    steps:
      - name: Wait for approval
        run: echo "Waiting for manual approval..."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy application
        run: |
          echo "Deploying application..."
          sudo apt install docker.io -y
          sudo docker stop sample-node-app || true
          sudo docker rm sample-node-app || true
          sudo docker build . -t sample-node-app
          docker run -itd --name sample-node-app -p 3000:3000 sample-node-app
          echo "Deployment complete!"

  failure-logger:
    runs-on: self-hosted
    needs: [build, deploy]
    if: failure()
    steps:
      - name: Capture failure logs
        run: |
          echo "Pipeline failed!" > failure.log
          echo "Time: $(date)" >> failure.log
          echo "GitHub Run ID: ${{ github.run_id }}" >> failure.log
          echo "Commit: ${{ github.sha }}" >> failure.log
          echo "Actor: ${{ github.actor }}" >> failure.log
      
      - name: Upload failure logs
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs
          path: failure.log
